[package]
name = "librarian"
version = "0.1.0"
authors = ["Julien Tregoat <jules@jules.nyc>"]
edition = "2018"

[dependencies]
tokio = {version = "0.3.3", features = ["fs", "sync"]}
sqlx = {version = "0.4.0-beta.1", default-features = false, features = ["runtime-tokio", "sqlite", "chrono", "macros", "migrate"]}
claxon = "0.4.2"
futures = "0.3.5"
chrono = "0.4"
hound = "3.4.0"
rtag = "0.3.5"
log = "0.4.8"
minimp3 = "0.3.5"
aiff = {git = "https://github.com/julientregoat/aiff-rs.git"}
# cpal # audio playback

[dev-dependencies]