[package]
name = "librarian"
version = "0.1.0"
authors = ["Julien Tregoat <jules@jules.nyc>"]
edition = "2018"

[lib]
name = 'librarian'

[dependencies]
tokio = {version = "0.3.4", features = ["fs", "sync"]}
sqlx = {version = "0.4.1", default-features = false, features = ["runtime-tokio-native-tls", "sqlite", "chrono", "macros", "migrate"]}
claxon = "0.4.3"
futures = "0.3.8"
chrono = "0.4"
hound = "3.4.0"
rtag = "0.3.5"
log = "0.4.11"
minimp3 = "0.3.5"
aiff = {git = "https://github.com/julientregoat/aiff-rs.git"}
cpal = "0.13.1"

[dev-dependencies]